
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
  name: bookinfo
spec:
  rules:
    - host: bookinfo.demo
      http:
        paths:
          - path: /
            backend:
              serviceName: productpage
              servicePort: 9080

