version: "3"

services:
  gateway-svc:
    image: registry.gitlab.com/hoanganhnguyen1994/ui-management:gateway-svc-v2
    container_name: "gateway-svc"
    build:
      context: "./services/service-management"
      dockerfile: Dockerfile.gateway-svc
    ports:
      - "3000:3000"
    environment:
      INGREDIENT_SVC_URL: "ingredient-svc:50051"
      RECIPE_SVC_URL: "recipe-svc:50052"
  ingredient-svc:
    image: registry.gitlab.com/hoanganhnguyen1994/ui-management:ingredient-svc-v2
    container_name: "ingredient-svc"
    build:
      context: "./services/service-management"
      dockerfile: Dockerfile.ingredient-svc
    expose:
      - "50051"
    environment:
      GRPC_HOST: "0.0.0.0"
      GRPC_PORT: "50050"
  recipe-svc:
    image: registry.gitlab.com/hoanganhnguyen1994/ui-management:recipe-svc-v2
    container_name: "recipe-svc"
    build:
      context: "./services/service-management"
      dockerfile: Dockerfile.recipe-svc
    expose:
      - "50052"
    environment:
      GRPC_HOST: "0.0.0.0"
      GRPC_PORT: "50050"
  ui-management-v2:
    image: registry.gitlab.com/hoanganhnguyen1994/ui-management:ui-management-v2
    container_name: "ui-management-v2"
    build:
      context: "./ui/ui-management-v2"
      dockerfile: Dockerfile.recipe-svc
    ports:
      - "5000:80"
    environment:
      API_URL: "http://simple.web"
