version: "3"

services:
  gateway-svc:
    image: registry.gitlab.com/hoanganhnguyen1994/ui-management:gateway-svc-v1
    container_name: "gateway-svc"
    build:
      context: "./services/service-management"
      dockerfile: Dockerfile.gateway-svc
    ports:
      - "3000:3000"
      - "3100:3100"
    environment:
      GATEWAY_SVC_PORT: 3000
      GATEWAY_SVC_HOST: "gateway-svc"
      INGREDIENT_SVC_PORT: 3001
      INGREDIENT_SVC_HOST: "ingredient-svc"
      RECIPE_SVC_PORT: 3002
      RECIPE_SVC_HOST: "recipe-svc"
  ingredient-svc:
    image: registry.gitlab.com/hoanganhnguyen1994/ui-management:ingredient-svc-v1
    container_name: "ingredient-svc"
    build:
      context: "./services/service-management"
      dockerfile: Dockerfile.ingredient-svc
    ports:
      - "3101:3101"
      - "3001:3001"
    environment:
      INGREDIENT_SVC_PORT: 3001
      INGREDIENT_SVC_HOST: "ingredient-svc"
  recipe-svc:
    image: registry.gitlab.com/hoanganhnguyen1994/ui-management:recipe-svc-v1
    container_name: "recipe-svc"
    build:
      context: "./services/service-management"
      dockerfile: Dockerfile.recipe-svc
    ports:
      - "3102:3102"
      - "3002:3002"
    environment:
      RECIPE_SVC_PORT: 3002
      RECIPE_SVC_HOST: "recipe-svc"
