version: "3"

services:
  gateway-svc:
    image: "gateway-svc"
    container_name: "gateway-svc"
    build:
      context: "./services/service-management"
      dockerfile: Dockerfile.gateway-svc
    ports:
      - "3000:3000"
    environment:
      INGREDIENT_SVC_URL: "ingredient-svc:50051"
      RECIPE_SVC_URL: "recipe-svc:50052"
  ingredient-svc:
    image: "ingredient-svc"
    container_name: "ingredient-svc"
    build:
      context: "./services/service-management"
      dockerfile: Dockerfile.ingredient-svc
    expose:
      - "50051"
    environment:
      GRPC_HOST: "0.0.0.0"
      GRPC_PORT: "50050"
  recipe-svc:
    image: "recipe-svc"
    container_name: "recipe-svc"
    build:
      context: "./services/service-management"
      dockerfile: Dockerfile.recipe-svc
    expose:
      - "50052"
    environment:
      GRPC_HOST: "0.0.0.0"
      GRPC_PORT: "50050"
