
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
  name: simple-ui
spec:
  rules:
    - host: simple.ui
      http:
        paths:
          - path: /
            backend:
              serviceName: simple.ui
              servicePort: 80

