
apiVersion: v1
kind: Service
metadata:
  name: simple-ui
  labels:
    app: simple-ui
spec:
  type: ClusterIP
  selector:
    app: simple-web
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
