apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingredient-db
  namespace: demo
  labels:
    app: ingredient-db
spec:
  selector:
    matchLabels:
      app: ingredient-db
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: ingredient-db
    spec:
      containers:
        - name: ingredient-db
          image: redis
          ports:
            - containerPort: 6379

