
FROM registry.gitlab.com/hcg-openhub/hcg-hub/hcg-node:14-alpine as bundle

WORKDIR /usr/src/api-ingredient

COPY dist/apps/ingredient-svc .
COPY package.json .

RUN npm install --production

EXPOSE 50051

CMD ["node", "main.js"]

