
FROM registry.gitlab.com/hcg-openhub/hcg-hub/hcg-node:14-alpine as bundle

WORKDIR /usr/src/api-recipe

COPY dist/apps/recipe-svc .
COPY package.json .

RUN npm install --production

EXPOSE 50052

CMD ["node", "main.js"]


