kind: Service
apiVersion: v1
metadata:
  name: recipe-svc
  labels:
    app: recipe-svc
spec:
  type: ClusterIP
  selector:
    app: recipe-svc
  ports:
    - name: grpc
      port: 80
      targetPort: 50052
      protocol: TCP

