apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-svc
  labels:
    app: recipe-svc
    version: v1
spec:
  selector:
    matchLabels:
      app: recipe-svc
      version: v1
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: recipe-svc
        version: v1
    spec:
      containers:
        - env:
            - name: GRPC_HOST
              value: "0.0.0.0"
            - name: GRPC_PORT
              value: "50050"
            - name: INGREDIENT_SVC_URL
              value: ingredient-svc.demo.svc.cluster.local:80
          name: gateway-svc
          image: registry.gitlab.com/hoanganhnguyen1994/ui-management:recipe-svc-v1
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 50m
              memory: 150Mi
            limits:
              cpu: 100m
              memory: 300Mi
          ports:
            - name: http
              containerPort: 50052
              protocol: TCP
