#apiVersion: networking.istio.io/v1alpha3
#kind: VirtualService
#metadata:
#  name: gateway-svc
#spec:
#  hosts:
#    - gateway-svc.demo.svc.cluster.local
#  http:
#    - route:
#        - destination:
#            host: gateway-svc
#            subset: v1
#          weight: 10
#        - destination:
#            host: gateway-svc
#            subset: v2
#          weight: 90
#
---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: gateway-svc
spec:
  hosts:
    - api.simple.ui
  http:
    - route:
        - destination:
            host: gateway-svc
            subset: v2
          weight: 25
        - destination:
            host: gateway-svc
            subset: v1
          weight: 75
