apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: gateway-svc
spec:
  hosts:
    - api.simple.ui
  http:
    - route:
        - destination:
            host: gateway-svc
            subset: v1
          weight: 50
        - destination:
            host: gateway-svc
            subset: v2
          weight: 50

