apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: gateway-svc
spec:
  hosts:
    - api.simple.ui/
  http:
    - match:
        - uri:
            prefix: /
          headers:
            cookie:
              regex: ^(.*?;)?(version=v2)(;.*)?$
      route:
        - destination:
            host: gateway-svc
            subset: v2
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: gateway-svc
            subset: v1

