apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: gateway-svc
spec:
  hosts:
    - simple.ui
  http:
    - route:
        - destination:
            host: gateway-svc.demo.svc.cluster.local
            subset: v1
          weight: 80
        - destination:
            host: gateway-svc.demo.svc.cluster.local
            subset: v2
          weight: 20

---

#apiVersion: networking.istio.io/v1alpha3
#kind: VirtualService
#metadata:
#  name: gateway-svc
#spec:
#  hosts:
#    - gateway-svc.demo.svc.cluster.local
#  http:
#    - match:
#        - uri:
#            prefix: /api
#      route:
#        - destination:
#            host: gateway-svc.demo.svc.cluster.local
#            subset: v1
#          weight: 80
#        - destination:
#            host: gateway-svc.demo.svc.cluster.local
#            subset: v2
#          weight: 20

---

#apiVersion: networking.istio.io/v1alpha3
#kind: VirtualService
#metadata:
#  name: gateway-svc
#spec:
#  hosts:
#    - simple.ui
#  tcp:
#    - route:
#        - destination:
#            host: gateway-svc
#            port:
#              number: 80
#            subset: v1
