
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: gateway-svc
spec:
  host: gateway-svc.demo.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: gateway-svc-v1
    labels:
      version: v1
  - name: gateway-svc-v2
    labels:
      version: v2

