apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: gateway-svc
  namespace: demo
spec:
  rules:
    - host: simple.ui
      http:
        paths:
          - path: /api/client(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: gateway-svc
                port:
                  number: 3000

---

#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  annotations:
#    kubernetes.io/ingress.class: "nginx"
#    nginx.ingress.kubernetes.io/ssl-redirect: "false"
#  name: gateway-svc
#  namespace: demo
#spec:
#  rules:
#    - host: simple.api
#      http:
#        paths:
#          - path: /
#            pathType: Prefix
#            backend:
#              service:
#                name: gateway-svc-v1
#                port:
#                  number: 3000

