apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-svc-v1
  namespace: demo
  labels:
    app: gateway-svc
    version: v1
spec:
  selector:
    matchLabels:
      app: gateway-svc
      version: v1
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: gateway-svc
        version: v1
    spec:
      containers:
        - name: gateway-svc
          image: registry.gitlab.com/hoanganhnguyen1994/ui-management:gateway-svc-v1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: GATEWAY_SVC_PORT
              value: "3000"
