
apiVersion: v1
kind: Service
metadata:
  name: gateway-svc
  labels:
    app: gateway-svc
spec:
  type: ClusterIP
  selector:
    app: gateway-svc
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---

