
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: simple-ui
spec:
  hosts:
    - simple.ui
  http:
    - route:
        - destination:
            host: simple-ui
            subset: v1
          weight: 80
        - destination:
            host: simple-ui
            subset: v2
          weight: 20
