
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: simple-ui
spec:
  host: simple-ui.demo.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2

